version: 0.2
phases:
  pre_build:
    commands:
      - dotnet restore slnTestCodePipeline/service/service.csproj    
  build:
    commands:
      - dotnet publish -c release -o ./build_output  slnTestCodePipeline/service/service.csproj 
artifacts:
  files:
    - slnTestCodePipeline/service/build_output/**/*
    - scripts/**/*
